### ISSUE TITLE
Major bug shutdown whole script

### ISSUE THREAD

**Issue by Walshor** [johnnyawesome/Adventure.Land#4]
The script works fine for a few hours, then suddenly an error occurs and it will not be able to run anymore.
The problem is likely to be in: **handleFarming.9** at **monsterBoundary**

![job](https://user-images.githubusercontent.com/84254450/118381894-04120380-b5f0-11eb-9f84-7bb4577a52f3.jpg)

**Comment by Tripweeze** [comment]
Possible quick fix--I think you can circumvent this monsterBoundary issue by using try...catch on the first await smart_move(farmingSpotData) in the async function merchantRound() (merchantSkills.js module). I did not even pass the exception to an error handler but just used return.

**Comment by Walshor** [comment]
I figured out how this error arises - sometimes two characters take a quest and the script doesn't know which to do and it enters infinite loop.
Quick fix is disable quest (const hunterToggle = false;) until quest's time is up - when the characters will not have duble quests infinite loop will end.

I just don't know how to improve the logic so that the characters don't take two quests or get stuck when take a few.

**Comment by johnnyawesome** [comment]
Hi Guys

First of, thank you both for the Bug-Report and your inputs!
I encountered this bug myself, but wasn't even able to pinpoint it - great work of you both. 👍

When you say "sometimes two characters take a quest" you mean hunting-Quests, right?

The game only lets you take one hunting-quest per character at the time. One character cannot have two active hunter-quests.

All characters write their (own) Hunter-Quests into LocalStorage, inside "cstore_huntedMonsters". (I use LocalStorage, because all characters can access it. This way, all characters can help doing the same quest. "cstore_huntedMonsters" holds an Array of all active Hunter-Quests. (New ones get added at the beginning [0]) All characters always pick the last quest in the Array.)

I'd love to fix it, but I don't even understand the problem yet. :)
(Setting "hunterToggle = false" will disable hunter-quests entirely. They won't go and get a new quest if I disable it).

Can you please go in more detail?  "so that the characters don't take two quests or get stuck when take a few" - they really shouldn't. That's why they always pick the last one inside the array.

With "double quests" you mean that there are multiple hunter-quests inside "cstore_huntedMonsters", yes?

**Comment by Walshor** [comment]
Yes im mean hunting-Quests.

It looks like sometimes the script can't decide what to do when it has several quests on different characters when there is no permission to kill the monsters in quest's.

When I logged in manually on each character two out of three they had quests not added in 'allowedMonsters' - that is, they couldn't make them and script go in infinity loop.

As the characters had only one quest with not allowed monsters it's all works fines and team go for 'MonstersToFarm' but the problem began to arise when several impossible quests appear - because the script doesn't know what to do.

When one of the two impossible quests timer has run out, everything starts working properly. 

So it looks like the variable is missing what to do if more than one quest cannot be done ( according to allowedMonsters).

**Comment by johnnyawesome** [comment]
Weird. I set `const allowedMonsters = [];` so all monsters are disallowed, no problem, they farmed what they should.
Then I set `const allowedMonsters = ["rat"];` (because one character had a quest for it, the others had different quests) and still nothing.

Then I checked with this:

`const allowedMonsters = [
	"hen", "rooster", "goo", "crab", "bee", "minimush", "frog",
	"squigtoad", "osnake", "snake", "rat", "armadillo", "croc",
	"squig", "cgoo", "poisio", "porcupine", "arcticbee", "spider",
	"tortoise", "stoneworm", "bat", "scorpion", "iceroamer",
	"crabx", "jr", "greenjr", "bbpompom", "boar", "ghost",
	"mole", "wolfie", "wolf", "xscorpion", "bigbird",
	"plantoid", "mechagnome"];

function getFarmingSpotData(farmMonsterType = "crab") {

	//Special logic to hunt rare Event-Monsters
	if (eventMonsters.includes(farmMonsterType)) {
		return findEventMonsters("getFarmingSpotData");
		//If farmMonsterType has special (hardcoded) Spawn, return that
	} else if (Object.keys(specialSpawns).includes(farmMonsterType)) {
		return specialSpawns[farmMonsterType];
		//Dynamically calculated Spawns. Nice.
	} else {

		const availableMaps = [
			"main",
			"woffice",
			"tunnel",
			"bank",
			"cave",
			"arena",
			"tavern",
			"mansion",
			"level1",
			"hut",
			"halloween",
			"mtunnel",
			"test",
			"cyberland",
			"winterland",
			"desertland",
			"resort_e",
			"level2",
			"spookytown",
			"winter_inn",
			"winter_cave",
			"level2n",
			"level2s",
			"level3",
			"level2e",
			"level2w",
			"winter_inn_rooms",
			"level4"
		];
		//Find all spawns of the monster
		let farmingSpots = [];
		for (map in G.maps) {
			if (!availableMaps.includes(map)) continue;
			for (monsters in G.maps[map].monsters) {
				let monster = G.maps[map].monsters[monsters];
				if (monster.type === farmMonsterType) {
					farmingSpots.push({
						map: map,
						monster: monster
					});
				}
			}
		}
		//Find the spawn with most monsters
		let mostMonsters = 0;
		let indexMostMonsters = 0;
		farmingSpots.forEach((farmingSpot, index) => {
			if (farmingSpot.monster.count > mostMonsters) {
				mostMonsters = farmingSpot.monster.count;
				indexMostMonsters = index;
			}
		});


		//###################### Returns farmingSpotData ######################

		//Max Kiting Radius
		const maxRadius = (masterMaxDist / 2) - 2;
		//monsterBoundary holds the boundaries of the monster-spawn (for better readability)
		const monsterBoundary = farmingSpots[indexMostMonsters]?.monster?.boundary;
		//Half of X and Y of monsterBoundary [The rectangle monsters spawn in]
		const farmSpotCenterX = Math.floor(monsterBoundary[0] + ((monsterBoundary[2] - monsterBoundary[0]) / 2));
		const farmSpotCenterY = Math.floor(monsterBoundary[1] + ((monsterBoundary[3] - monsterBoundary[1]) / 2));

		//Returns (dynamic) Monster Spawn
		return {
			map: farmingSpots[indexMostMonsters].map,
			x: farmSpotCenterX,
			y: farmSpotCenterY,
			//Kiting Radii
			xRadius: (Math.floor((monsterBoundary[2] - monsterBoundary[0]) / 2) > maxRadius) ? maxRadius : Math.floor((monsterBoundary[2] - monsterBoundary[0]) / 2),
			yRadius: (Math.floor((monsterBoundary[3] - monsterBoundary[1]) / 2) > maxRadius) ? maxRadius : Math.floor((monsterBoundary[3] - monsterBoundary[1]) / 2)
		}
	}
}

let result = [];

allowedMonsters.forEach(monster => {
	result.push(monster)
	result.push(getFarmingSpotData(monster))
});

show_json(result)` 

It gives back good results for each monster.

I'm puzzled. I can't figure out what the problem is. 😅

**Comment by Walshor** [comment]
It seems like a crazy idea, but maybe the error arises because there are empty field?

This is what my configuration looks like when an error occurs :

> const allowedMonsters = [
> 	"hen", "rooster", "goo", "crab", "bee", "cutebee", "minimush", "",
> 	"squigtoad", "", "snake", "rat", "armadillo", "croc", "squig",
> 	"poisio", "scorpion", "porcupine", "arcticbee", "spider", "tortoise",
> 	"scorpion", "bat", "goldenbat", "wabbit", "", "",
> 	"", "", "", "", "", "", "",
> 	"", "", "", "", "",
> 	"", "", "", ""];

Here are other settings with available monsters

> 
> const specialMonsters = ["cutebee", "snowman", "goldenbat",
> 	"wabbit", "", "", "", ""];
> 
> const eventMonsters = ["wabbit", "snowman", ""];

Or that Special and Event monsters are not added  to 'allowedMonsters' ?

**Comment by johnnyawesome** [comment]
That's probably not it,. but I deleted the empty spaces on my end anyways, it's cleaner.

I think we're going in the wrong direction.

Your first printscreen - which is super helpful by the way -says "monsterBoundary is undefined".

But the code I posted above throws all allowed monsters at `getFarmingSpotData()` and returns good results. It never returns `undefined`. I compated every single result with `allowedMonsters ` - none was missing.

**Comment by johnnyawesome** [comment]
I split the hunter-function into several separate functions. Works for me now. I'll wait a few days until I release it. Want to make sure it works properly and doesn't make things worse.

**Comment by johnnyawesome** [comment]
I fixed a bunch of bugs today , please get the latest version of the code.
(There were a few crashes that caused disconnects of the merchant (and therefor all characters). You should get the newest version of the code - it is fixed there.)
